export const FETCH_MUSIC = 'FETCH_MUSIC';
export const FETCH_MUSIC_REJECTED = 'FETCH_MUSIC_REJECTED';
export const FETCH_MUSIC_FULFILLED = 'FETCH_MUSIC_FULFILLED';
export const CHANGE_DISPLAY = 'CHANGE_DISPLAY';